name: animate-preview
version: '0.1.0'
github: jxv/animate-preview
license: BSD3
category: Game
synopsis: Preview tool for sprite animation
description: Preview tool for sprite animation
maintainer: Joe Vargas
copyright: 2018 Joe Vargas
data-files:
- resource/ProggyClean.ttf
extra-source-files:
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
default-extensions:
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- ScopedTypeVariables
- OverloadedStrings
- DefaultSignatures
- MultiParamTypeClasses
library:
  dependencies:
    - base >=4.7 && <5
    - aeson
    - animate
    - bytestring
    - containers
    - filepath
    - fsnotify
    - key-state
    - linear
    - lens
    - mtl
    - optparse-applicative
    - optparse-generic
    - random
    - safe
    - safe-exceptions
    - sdl2
    - sdl2-image
    - sdl2-ttf
    - sdl2-gfx
    - StateVar
    - text
    - text-conversions
    - vector
  source-dirs: library
executables:
  animate-preview:
    dependencies:
    - base >=4.7 && <5
    - animate-preview
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
